### ISSUE TITLE
how to

### ISSUE THREAD

**Issue by githiakalaban** [ParrotSec/apt-parrot#1]
how can i use this script ? any tutorial please !

**Comment by PalinuroSec** [comment]
https://www.parrotsec.org

this is reserved for internal use in parrot os

**Comment by githiakalaban** [comment]
thanks for the help :) i muted the thread
please would you help me with hacking book:pdfs ?

**Comment by PalinuroSec** [comment]
i believe this is the wrong place for this kind of questions

join our community groups if you need help
https://www.parrotsec.org/docs/community
